### ISSUE TITLE
Menüsorrend

### ISSUE THREAD

**Issue by ighcsakvar** [parphis/esterhazyiskola#131]
Szia István!

Ez a felület régen is jól működött. Ha neked is megfelel, újranyithatnánk. Egy dolgot be is írtam.

Peti

- [x] Az iskolai élet/Munkatársaink menün belül megjelenő almenük sorrendjében a Pszichológus fül mindig a végére ugrik, hiába viszem feljebb.

**Comment by parphis** [comment]
Szia Peti! Igen, írj ide nyugodtan, bármi gond van, igyekszem mihamarabb javítani, megcsinálni.
Ebben az esetben most az volt, hogy a `Mappa neve` beállítás a Pszichológusok képeinek oldalán nagybetűs Pszichologus volt. Mire rájöttem, jajj, hogy ez a gond... Ugyanis a Linux rendszerek alapértelmezetten úgy rendeznek abc sorrendben, hogy a kisbetűseket veszik előre, majd utána jönnek a nagybetűsek. És hiába mozgattuk ezt a menüpontot, az mindig alulra került, mert az összes többi kisbetűs mappanevű.
A lényeg, hogy most átírtam kis kezdőbetűsre a pszichologus mappanevet az admin felületen, és így lehet rendezni.
