### ISSUE TITLE
 Gmail naptárak létrehozása

### ISSUE THREAD

**Issue by parphis** [parphis/esterhazyiskola#17]
Csak naptáraknak készítettem egy Google fiókot:
https://account.google.com
user: emuesemenyek@gmail.com
Publikus ICAL URI: https://calendar.google.com/calendar/ical/emuesemenyek%40gmail.com/public/basic.ics

**Comment by parphis** [comment]
Készen van:
 * a csak calendar account, és benne teszt adatok.
 * A fejlécben a szöveg helyett a hónap képe látszik és változik is jól.
 * Az egész napos eseményeknél nincsen time slot helyén 00:00.

Függőben:
 * Az évek is képként jelenjenek meg.
 * A színkódok magyarázata szebben legyen látható.
 * Az egyes bejegyzéseknél ne a YYYY.MM.DD. legyen, csak a DD. és a nap neve egymás mellett.

**Comment by bendibanda** [comment]
A számok képei

![0](https://user-images.githubusercontent.com/63727751/103933812-44361680-5124-11eb-83e9-a5909dede43b.jpg)
![0](https://user-images.githubusercontent.com/63727751/103933817-44cead00-5124-11eb-9567-f94c893ac0e9.png)
![1](https://user-images.githubusercontent.com/63727751/103933819-45ffda00-5124-11eb-8e5e-758a2fb878ab.jpg)
![1](https://user-images.githubusercontent.com/63727751/103933822-45ffda00-5124-11eb-8aea-654f655d1861.png)
![2](https://user-images.githubusercontent.com/63727751/103933825-46987080-5124-11eb-9a80-0d8d3de4a85b.jpg)
![2](https://user-images.githubusercontent.com/63727751/103933827-47310700-5124-11eb-8ba5-a870d3f6aefa.png)
![3](https://user-images.githubusercontent.com/63727751/103933830-47c99d80-5124-11eb-95c3-2072a527878d.jpg)
![3](https://user-images.githubusercontent.com/63727751/103933833-47c99d80-5124-11eb-9ce6-a4e3998703ab.png)
![4](https://user-images.githubusercontent.com/63727751/103933834-48623400-5124-11eb-8d83-2c4a1b473b3a.jpg)
![4](https://user-images.githubusercontent.com/63727751/103933835-48faca80-5124-11eb-9835-35f020e96a54.png)
![5](https://user-images.githubusercontent.com/63727751/103933837-48faca80-5124-11eb-92dc-c7236b1e9eb1.jpg)
![5](https://user-images.githubusercontent.com/63727751/103933838-49936100-5124-11eb-8ea1-b7801e465ac4.png)
![6](https://user-images.githubusercontent.com/63727751/103933839-4a2bf780-5124-11eb-9911-b47ce61bc3cf.jpg)
![6](https://user-images.githubusercontent.com/63727751/103933840-4a2bf780-5124-11eb-8df6-acfa20577aab.png)
![7](https://user-images.githubusercontent.com/63727751/103933846-4ac48e00-5124-11eb-8f69-6a82cb379079.jpg)
![7](https://user-images.githubusercontent.com/63727751/103933847-4b5d2480-5124-11eb-8648-7a026cd5a396.png)
![8](https://user-images.githubusercontent.com/63727751/103933848-4b5d2480-5124-11eb-94fb-3b5cedcb352a.jpg)
![8](https://user-images.githubusercontent.com/63727751/103933849-4bf5bb00-5124-11eb-9979-f91121fd1f17.png)
![9](https://user-images.githubusercontent.com/63727751/103933851-4c8e5180-5124-11eb-9cd5-a9490b04961f.jpg)
![9](https://user-images.githubusercontent.com/63727751/103933852-4d26e800-5124-11eb-9963-01d95af010d4.png)
